version: '3'
services:
  gpt-researcher:
    image: kramer1346/gpt-researcher
    build: ./
    env_file:
      - .env
    ports:
      - 8001:8000
    networks:
      - petya_net

networks:
  petya_net: